clc;clear;close all
load cleaned-data.mat
figureHandle = figure;
hold on

subplot(2,4,1);
box = boxplot(data.supply,'Widths',0.7,...
    'Notch','on','Symbol','o','OutlierSize',5,'Jitter',0);
hTitle = title('全国城市(部分)售水量箱线图');
hYLabel = ylabel('售水量(万吨)');
set(box,'LineWidth',1.5)
set(box(1:2,:),'LineStyle','-')
set(gca, 'Box', 'off','LineWidth', 2,'XGrid', 'off', 'YGrid', 'on', ...               
         'TickDir', 'out', 'TickLength', [.015 .015], ... 
         'XColor', [.1 .1 .1],  'YColor', [.1 .1 .1], ...
         'Xlim',[0.5,1.5]) 
set(gca, 'FontName', 'Arial', 'FontSize', 9)
set(hYLabel, 'FontSize', 11, 'FontName', 'Arial')
set(hTitle, 'FontSize', 12, 'FontWeight' , 'bold')
set(gcf,'Color',[1 1 1])
xc = get(gca,'XColor');
yc = get(gca,'YColor');
unit = get(gca,'units');
ax = axes( 'Units', unit,...
           'Position',get(gca,'Position'),...
           'XAxisLocation','top',...
           'YAxisLocation','right',...
           'Color','none',...
           'XColor',xc,...
           'YColor',yc);
set(ax, 'linewidth',1,...
        'XTick', [],...
        'YTick', []);


subplot(2,4,2);
box = boxplot(data.consummerSupply,'Widths',0.7,...
    'Notch','on','Symbol','o','OutlierSize',5,'Jitter',0);
hTitle = title('全国城市(部分)居民售水量箱线图');
hYLabel = ylabel('售水量(万吨)');
set(box,'LineWidth',1.5)
set(box(1:2,:),'LineStyle','-')
set(gca, 'Box', 'off','LineWidth', 2,'XGrid', 'off', 'YGrid', 'on', ...               
         'TickDir', 'out', 'TickLength', [.015 .015], ... 
         'XColor', [.1 .1 .1],  'YColor', [.1 .1 .1], ...
         'Xlim',[0.5,1.5]) 
set(gca, 'FontName', 'Arial', 'FontSize', 9)
set(hYLabel, 'FontSize', 11, 'FontName', 'Arial')
set(hTitle, 'FontSize', 12, 'FontWeight' , 'bold')
set(gcf,'Color',[1 1 1])
xc = get(gca,'XColor');
yc = get(gca,'YColor');
unit = get(gca,'units');
ax = axes( 'Units', unit,...
           'Position',get(gca,'Position'),...
           'XAxisLocation','top',...
           'YAxisLocation','right',...
           'Color','none',...
           'XColor',xc,...
           'YColor',yc);
set(ax, 'linewidth',1,...
        'XTick', [],...
        'YTick', []);

subplot(2,4,3);
box = boxplot(data.resource,'Widths',0.7,...
    'Notch','on','Symbol','o','OutlierSize',5,'Jitter',0);
hTitle = title('全国城市(部分)水资源箱线图');
hYLabel = ylabel('水资源总量(万立方米)');
set(box,'LineWidth',1.5)
set(box(1:2,:),'LineStyle','-')
set(gca, 'Box', 'off','LineWidth', 2,'XGrid', 'off', 'YGrid', 'on', ...               
         'TickDir', 'out', 'TickLength', [.015 .015], ... 
         'XColor', [.1 .1 .1],  'YColor', [.1 .1 .1], ...
         'Xlim',[0.5,1.5]) 
set(gca, 'FontName', 'Arial', 'FontSize', 9)
set(hYLabel, 'FontSize', 11, 'FontName', 'Arial')
set(hTitle, 'FontSize', 12, 'FontWeight' , 'bold')
set(gcf,'Color',[1 1 1])
xc = get(gca,'XColor');
yc = get(gca,'YColor');
unit = get(gca,'units');
ax = axes( 'Units', unit,...
           'Position',get(gca,'Position'),...
           'XAxisLocation','top',...
           'YAxisLocation','right',...
           'Color','none',...
           'XColor',xc,...
           'YColor',yc);
set(ax, 'linewidth',1,...
        'XTick', [],...
        'YTick', []);


subplot(2,4,4);
box = boxplot(data.prep,'Widths',0.7,...
    'Notch','on','Symbol','o','OutlierSize',5,'Jitter',0);
hTitle = title('全国城市(部分)降水量箱线图');
hYLabel = ylabel('降水量(毫米)');
set(box,'LineWidth',1.5)
set(box(1:2,:),'LineStyle','-')
set(gca, 'Box', 'off','LineWidth', 2,'XGrid', 'off', 'YGrid', 'on', ...               
         'TickDir', 'out', 'TickLength', [.015 .015], ... 
         'XColor', [.1 .1 .1],  'YColor', [.1 .1 .1], ...
         'Xlim',[0.5,1.5]) 
set(gca, 'FontName', 'Arial', 'FontSize', 9)
set(hYLabel, 'FontSize', 11, 'FontName', 'Arial')
set(hTitle, 'FontSize', 12, 'FontWeight' , 'bold')
set(gcf,'Color',[1 1 1])
xc = get(gca,'XColor');
yc = get(gca,'YColor');
unit = get(gca,'units');
ax = axes( 'Units', unit,...
           'Position',get(gca,'Position'),...
           'XAxisLocation','top',...
           'YAxisLocation','right',...
           'Color','none',...
           'XColor',xc,...
           'YColor',yc);
set(ax, 'linewidth',1,...
        'XTick', [],...
        'YTick', []);

subplot(2,4,5);
histogram(data.supply,20);
title("全国城市(部分)售水量直方图",FontSize=12);
xlabel("售水量(万吨)");
ylabel("城市数量(个)");

subplot(2,4,6);
histogram(data.supply,20);
title("全国城市(部分)居民售水量直方图",FontSize=12);
xlabel("售水量(万吨)");
ylabel("城市数量(个)");

subplot(2,4,7);
histogram(data.resource,20);
title("全国城市(部分)水资源直方图",FontSize=12);
xlabel("水资源总量(万立方米)");
ylabel("城市数量(个)");

subplot(2,4,8);
histogram(data.prep,20);
title("全国城市(部分)降水量直方图",FontSize=12);
xlabel("降水量(毫米)");
ylabel("城市数量(个)");
